language: node_js
node_js:
- node
notifications:
  email: false
addons:
  ssh_known_hosts:
  - github.com
  - devschile.cl
before_deploy:
- openssl aes-256-cbc -K $encrypted_f6d50c2161ea_key -iv $encrypted_f6d50c2161ea_iv
  -in id_awesome.enc -out id_awesome -d
- eval "$(ssh-agent -s)"
- chmod 600 id_awesome
- ssh-add id_awesome
script:
- echo 'No tests'
deploy:
  provider: script
  script: git remote add dokku dokku@devschile.cl:awesome && git push dokku master
  skip_cleanup: true
  on:
    branch: master
