---
language: node_js
node_js:
  - node
notifications:
  email: false
addons:
  ssh_known_hosts:
    - github.com
    - devschile.cl
before_deploy:
  - openssl aes-256-cbc -K $encrypted_9e50b4071479_key -iv $encrypted_9e50b4071479_iv -in id_awesome_devschile.enc -out id_awesome_devschile -d
  - eval "$(ssh-agent -s)"
  - chmod 600 id_awesome_devschile
  - ssh-add id_awesome_devschile
script:
  - echo 'No tests'
deploy:
  provider: script
  script: git remote add dokku dokku@devschile.cl:awesome && git push dokku master
  skip_cleanup: true
  on:
    branch: master
